### PR TITLE
Restructuring and Editing of the function

### PR DESCRIPTION
**Pull request by stamats**
Should still give the same results as the original function. Adeline please verify.

### CODE REVIEW

**Comment by adeline-torey** [comment]
I compared original and edited, using 2 data sets.
Both original and edited codes returned the same results.
The test is documented in my [Master_thesis repository](https://github.com/AdelineTorey/Master_thesis/blob/master/experiments/10.04%20-%20Compare%20stamats-patch-1%20with%20master%20-%20NanoPrepareM.R)

@stamats Should I accept the pull request then?

**Comment by stamats** [comment]
Thank you!
Yes, you could accept the pull request.
I still don't understand, why "nr.rows.last" (resp. howmany_) is negative.

**Comment by adeline-torey** [comment]
Thank you.

I'm not sure about the negative either. When I ran the code without the negative sign, the result was different.

I'm not exactly sure what is being done in the rhdf5 section. From what I understand, first, the files are ordered, then, the number of rows (which I think represents the reads) are extracted from the first and last files and computed in the formula to get the number of reads. 

But I'm not sure exactly why only the first and last files are considered.

I tried to look at the fast.5 file using hdfview too look at the information contained but there is no way to organise the files or count the number of reads. I've attached a screenshot of the fast.5 file in hdfview.
skip-fast5-hdfview

**Comment by stamats** [comment]
Assuming that all files except for the last one have the same size, the code would determine the number of rows of all files, but only if "nr.rows.last" would be positive. Do all files except for the last one indeed have the same size?

**Comment by adeline-torey** [comment]
According to page 5 of [this document by ONT](https://nanoporetech.com/sites/default/files/s3/MinION-Computer-Requirements-March-17_Final.pdf),
> "As many as 2 million read files have been produced during a sequencing experiment. These are stored in sub-folders containing 4000 reads each."

Is that what you meant?

I'm not very sure what sub-folders they are referring to. Is it the fast5 files? If it is, then I guess all files except the last one do have the same size. However, I could not find this information in any published article.

I could try to verify this by looking at the fast5 files I have.

**Comment by stamats** [comment]
Yes, it looks like there are at most 4000 reads per file; see
https://community.nanoporetech.com/requirements_documents/minion-it-reqs.pdf

Hence, it would make sense that one only needs to look at the first and last file.

We could also try to ask Davide Bolognini the original author of the package.

**Comment by adeline-torey** [comment]
Oh, yes, that makes sense. It's not necessary to consider the files in
between since their lengths are the same. So, it's enough to use multiples
of the first.
Thank you!

Yes, we could ask him. Should I write him an email?

**Comment by stamats** [comment]
Yes, please.

**Comment by adeline-torey** [comment]
Okay, I've sent an email.

**Comment by adeline-torey** [comment]
Dear Prof Kohl,

Davide has provided an explanation for the section of the code.

1. Should I ask him if he'd like to pull the changes we made?
2. Is it okay to tell him that we're working on improving the NanoR code?

Kind regards,
Adeline Torey

**Comment by stamats** [comment]
Dear Adeline,

ad 1. I would first collect all our changes and then he can decide, whether and which of our changes he wants to take over. 

ad 2. Yes, we should tell him that we are working through his code and that we, with his package as starting point, are trying to establish the whole data analysis workflow in R/Bioconductor.

Best regards,
Matthias Kohl

**Comment by adeline-torey** [comment]
Dear Prof Kohl,

okay.
Thank you very much.

Kind regards,
Adeline Torey

**Pull request merged**
